apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: marketing-app-health-check
  namespace: marketing-dev
spec:
  metrics:
    - name: preview-health
      successCondition: result == 200
      failureLimit: 1
      provider:
        web:
          url: http://marketing-app-preview.marketing-dev.svc.cluster.local/
          timeoutSeconds: 10