apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: marketing-app-vs
spec:
  hosts:
    - placeholder.com
  gateways:
    - marketing-app-gateway
  http:
    - route:
        - destination:
            host: marketing-app-blue
            port:
              number: 80
          weight: 100
        - destination:
            host: marketing-app-green
            port:
              number: 80
          weight: 0