apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: marketing-app-vs
  namespace: marketing-dev
spec:
  hosts:
    - pfechaima.duckdns.org
  gateways:
    - marketing-app-gateway
  http:
    - route:
        - destination:
            host: marketing-app-active
            port:
              number: 80