apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pfechaima-cert
  namespace: istio-system
spec:
  secretName: pfechaima-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pfechaima.duckdns.org