apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketing-dev

resources:
  - ../../base
  - namespace.yaml
  - certificate.yaml

patches:
  - path: patch-gateway.yaml
  - path: patch-virtualservice.yaml

images:
  - name: europe-west1-docker.pkg.dev/pfe-devsecops-490219/dev-docker-repo/livestream-server
    newTag: a0a0b469a697e0fdf3d07a3eb4d99b0c5aa02aa5

