apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketing-dev

resources:
  - ../../base
  - namespace.yaml
  - certificate.yaml

patches:
  - path: patch-gateway.yaml
  - path: patch-virtualservice.yaml

images:
  - name: europe-west1-docker.pkg.dev/pfe-devsecops-490219/dev-docker-repo/livestream-server
    newTag: 2a87e82712723191e6d545dc6eb5e9255afb0c5d

