apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policy-disallow-root.yaml
  - policy-require-resources.yaml
  - policy-allowed-registry.yaml
  - policy-disallow-latest-tag.yaml
  - policy-require-security-context.yaml